site_name: Sinsiway QA Release Note
theme: readthedocs
#theme:
#    name: 'rtd-dropdown'

nav:
  - Home: index.md
  - About: about.md
  - How: how.md
  - chapter1:
    - 1-1 : chapter1/1-1.md
    - 1-2 : chapter1/1-2.md  

plugins:
    - search
    - git-revision-date-localized
